version: '3'
services:
  nextflow-genomic:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./files:/app/files
      - ./results:/app/results
      - ./logs:/app/logs
    entrypoint: /bin/bash
    command: ["-c", "sleep infinity"]
